from django.urls import path

from .views import (
    CommonReactionListView,
    GeneralReactionDetailView,
    GeneralReactionListView,
    DeployGuideView,
    FeedbackView,
    HomeView,
    LearningResourceListView,
    MarkAllMessagesReadView,
    MessageDetailView,
    MessageListView,
    ProfileView,
    ReactionDetailView,
    ReactionListView,
    RegisterView,
    RouteDetailView,
    RouteListView,
    SaveNoteView,
    SubmitCommentView,
    ToggleFavoriteView,
    UpdateProgressView,
    ReactionComparisonDetailView,
    ReactionComparisonListView,
    StudyTopicDetailView,
    StudyTopicListView,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("feedback/", FeedbackView.as_view(), name="feedback"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("favorite/toggle/", ToggleFavoriteView.as_view(), name="toggle_favorite"),
    path("note/save/", SaveNoteView.as_view(), name="save_note"),
    path("progress/update/", UpdateProgressView.as_view(), name="update_progress"),
    path("comment/submit/", SubmitCommentView.as_view(), name="submit_comment"),
    path("messages/", MessageListView.as_view(), name="messages"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("messages/read-all/", MarkAllMessagesReadView.as_view(), name="mark_all_read"),
    path("deploy/", DeployGuideView.as_view(), name="deploy_guide"),
    path("reactions/", ReactionListView.as_view(), name="reaction_list"),
    path("reactions/common/", CommonReactionListView.as_view(), name="common_reaction_list"),
    path("reactions/general/", GeneralReactionListView.as_view(), name="general_reaction_list"),
    path("reactions/general/<slug:slug>/", GeneralReactionDetailView.as_view(), name="general_reaction_detail"),
    path("reactions/<slug:slug>/", ReactionDetailView.as_view(), name="reaction_detail"),
    path("routes/", RouteListView.as_view(), name="route_list"),
    path("routes/<slug:slug>/", RouteDetailView.as_view(), name="route_detail"),
    path("learning-resources/", LearningResourceListView.as_view(), name="learning_resource_list"),
    path("study-topics/", StudyTopicListView.as_view(), name="study_topic_list"),
    path("study-topics/<slug:slug>/", StudyTopicDetailView.as_view(), name="study_topic_detail"),
    path("reaction-comparisons/", ReactionComparisonListView.as_view(), name="reaction_comparison_list"),
    path("reaction-comparisons/<slug:slug>/", ReactionComparisonDetailView.as_view(), name="reaction_comparison_detail"),
]
