# Generated by Django 5.2.16 on 2026-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='资料标题')),
                ('category', models.CharField(choices=[('past_exam', '真题'), ('exercise', '习题'), ('answer', '答案'), ('courseware', '课件'), ('lecture', '讲义'), ('syllabus', '大纲'), ('book', '教材/复习书'), ('other', '其他')], default='other', max_length=30, verbose_name='分类')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='年份')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('local_path', models.TextField(unique=True, verbose_name='本地路径')),
                ('relative_path', models.TextField(blank=True, verbose_name='相对路径')),
                ('source_folder', models.CharField(blank=True, max_length=120, verbose_name='来源文件夹')),
                ('has_answer', models.BooleanField(default=False, verbose_name='含答案')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习资料',
                'verbose_name_plural': '学习资料',
                'ordering': ['category', '-year', 'title'],
                'indexes': [models.Index(fields=['status'], name='reactions_l_status_0bd656_idx'), models.Index(fields=['category'], name='reactions_l_categor_3cec0f_idx'), models.Index(fields=['year'], name='reactions_l_year_739bc1_idx'), models.Index(fields=['file_type'], name='reactions_l_file_ty_c22e0a_idx')],
            },
        ),
    ]
