# Generated by Django 5.2.16 on 2026-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_learningresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='structure_image',
            field=models.FileField(blank=True, upload_to='reaction_structures/', verbose_name='结构式图片'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='structure_image_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='结构式图片说明'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='structure_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='结构式图片 URL'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='product_structure_image',
            field=models.FileField(blank=True, upload_to='route_step_structures/', verbose_name='产物结构式图片'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='product_structure_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='产物结构式图片 URL'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='reactant_structure_image',
            field=models.FileField(blank=True, upload_to='route_step_structures/', verbose_name='反应物结构式图片'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='reactant_structure_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='反应物结构式图片 URL'),
        ),
        migrations.AddField(
            model_name='routestep',
            name='structure_image_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='步骤结构式说明'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='target_structure_image',
            field=models.FileField(blank=True, upload_to='route_structures/', verbose_name='目标产物结构式图片'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='target_structure_image_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='目标产物结构式说明'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='target_structure_image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='目标产物结构式图片 URL'),
        ),
    ]
