# Generated by Django 5.2.16 on 2026-07-29 02:57

import reactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_reaction_structure_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='equation_img',
            field=models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('equation'), verbose_name='反应方程式图片'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='mechanism_img',
            field=models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('mechanism'), verbose_name='反应机理图片'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='thumbnail_img',
            field=models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('thumbnail'), verbose_name='缩略图'),
        ),
    ]
