# Generated by Django 5.2.16 on 2026-07-29 07:07

import reactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_reaction_equation_img_reaction_mechanism_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='equation_smiles',
        ),
        migrations.RemoveField(
            model_name='routestep',
            name='product_smiles',
        ),
        migrations.RemoveField(
            model_name='routestep',
            name='reactant_smiles',
        ),
        migrations.RemoveField(
            model_name='syntheticroute',
            name='target_smiles',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='equation_img',
            field=models.FileField(blank=True, help_text='上传反应方程式的 SVG 或 PNG 图片', upload_to=reactions.models.ReactionImageUploadTo('equation'), verbose_name='反应方程式图片'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='mechanism_img',
            field=models.FileField(blank=True, help_text='上传机理图的 SVG 或 PNG 图片', upload_to=reactions.models.ReactionImageUploadTo('mechanism'), verbose_name='反应机理图片'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='thumbnail_img',
            field=models.FileField(blank=True, help_text='上传缩略图，用于列表页和卡片展示', upload_to=reactions.models.ReactionImageUploadTo('thumbnail'), verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='routestep',
            name='product_structure_image',
            field=models.FileField(blank=True, help_text='上传产物结构式的 SVG 或 PNG', upload_to='route_step_structures/', verbose_name='产物结构式图片'),
        ),
        migrations.AlterField(
            model_name='routestep',
            name='reactant_structure_image',
            field=models.FileField(blank=True, help_text='上传反应物结构式的 SVG 或 PNG', upload_to='route_step_structures/', verbose_name='反应物结构式图片'),
        ),
        migrations.AlterField(
            model_name='syntheticroute',
            name='target_structure_image',
            field=models.FileField(blank=True, help_text='上传目标产物结构式的 SVG 或 PNG 图片', upload_to='route_structures/', verbose_name='目标产物结构式图片'),
        ),
        migrations.AlterField(
            model_name='syntheticroute',
            name='target_structure_image_url',
            field=models.CharField(blank=True, help_text='已有图床路径时填写，例如 /static/images/routes/route_xxx.svg', max_length=500, verbose_name='目标产物结构式图片 URL'),
        ),
    ]
