# Generated by Django 5.2.16 on 2026-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_remove_reaction_equation_smiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='电子邮件')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
