# Generated by Django 5.2.16 on 2026-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_announcement_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='importance',
            field=models.CharField(choices=[('low', '普通'), ('high', '重要')], default='low', max_length=10, verbose_name='重要性'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='置顶公告始终显示在顶部，且不设显示时限', verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_from',
            field=models.DateTimeField(blank=True, help_text='非置顶公告：在此时间之后才显示', null=True, verbose_name='开始显示'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_until',
            field=models.DateTimeField(blank=True, help_text='非置顶公告：在此时间之后自动隐藏', null=True, verbose_name='截止显示'),
        ),
    ]
