# Generated by Django 5.2.16 on 2026-07-29 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0008_studynote_favorite_studyprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('content', '内容纠错'), ('feature', '功能建议'), ('data', '数据补充'), ('usage', '使用问题'), ('other', '其他')], default='other', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='internal_note',
            field=models.TextField(blank=True, help_text='仅管理员可见', verbose_name='内部备注'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, help_text='此回复将对用户可见', verbose_name='管理员回复'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('announcement', '公告通知'), ('feedback_reply', '反馈回复'), ('feedback_status', '反馈状态更新'), ('review_notice', '审核通知'), ('system', '系统提醒')], max_length=30, verbose_name='消息类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('related_url', models.CharField(blank=True, max_length=500, verbose_name='相关链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'ordering': ['-created_at'],
            },
        ),
    ]
