# Generated by Django 5.2.16 on 2026-07-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0009_feedback_category_feedback_handled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url_name', models.CharField(help_text='Django URL name，例如 reaction_list', max_length=100, verbose_name='URL 名称')),
                ('url_params', models.CharField(blank=True, help_text='查询参数，例如 ?tag=exam-high-frequency', max_length=200, verbose_name='URL 参数')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='前台显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
