# Generated by Django 5.2.16 on 2026-07-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0011_oplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='is_common',
            field=models.BooleanField(default=False, help_text='勾选后该反应出现在常见反应列表中', verbose_name='常见反应'),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='local_path',
            field=models.TextField(help_text='如需树形展示，按 分类/年份/文件名 的目录结构组织路径', unique=True, verbose_name='本地路径'),
        ),
    ]
