# Generated by Django 5.2.16 on 2026-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0012_reaction_is_common_alter_learningresource_local_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100, verbose_name='反应名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('content', models.TextField(blank=True, help_text='反应机理、要点说明等', verbose_name='内容说明')),
                ('equation_img', models.FileField(blank=True, upload_to='common_reactions/', verbose_name='反应方程式图片')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常见反应（非人名）',
                'verbose_name_plural': '常见反应（非人名）',
                'ordering': ['sort_order', 'name_zh'],
            },
        ),
    ]
