# Generated by Django 5.2.16 on 2026-08-02 13:47

import django.db.models.deletion
import reactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0013_commonreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '常见有机反应分类',
                'verbose_name_plural': '常见有机反应分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NamedReactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '人名反应分类',
                'verbose_name_plural': '人名反应分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='external_path',
            field=models.TextField(blank=True, verbose_name='外部路径'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_type',
            field=models.CharField(choices=[('upload', '上传文件'), ('external', '外部路径')], default='external', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='learning_resources/', verbose_name='上传文件'),
        ),
        migrations.CreateModel(
            name='GeneralReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=120, verbose_name='中文名')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='英文名')),
                ('aliases', models.CharField(blank=True, max_length=300, verbose_name='别名')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('condition', models.TextField(blank=True, verbose_name='反应条件')),
                ('mechanism', models.TextField(blank=True, verbose_name='机理描述')),
                ('exam_tips', models.TextField(blank=True, verbose_name='考研考点')),
                ('scope', models.TextField(blank=True, verbose_name='适用范围')),
                ('limitations', models.TextField(blank=True, verbose_name='使用限制')),
                ('reference', models.TextField(blank=True, verbose_name='参考来源')),
                ('equation_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('equation'), verbose_name='反应方程式图')),
                ('mechanism_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('mechanism'), verbose_name='机理图')),
                ('thumbnail_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('thumbnail'), verbose_name='缩略图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('functional_groups', models.ManyToManyField(blank=True, to='reactions.functionalgroup', verbose_name='官能团')),
                ('tags', models.ManyToManyField(blank=True, to='reactions.tag', verbose_name='标签')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='reactions.generalreactioncategory', verbose_name='常见有机反应分类')),
            ],
            options={
                'verbose_name': '常见有机反应',
                'verbose_name_plural': '常见有机反应',
                'ordering': ['name_zh', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='routestep',
            name='related_general_reactions',
            field=models.ManyToManyField(blank=True, related_name='route_steps', to='reactions.generalreaction', verbose_name='相关常见有机反应'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='related_general_reactions',
            field=models.ManyToManyField(blank=True, related_name='routes', to='reactions.generalreaction', verbose_name='相关常见有机反应'),
        ),
        migrations.CreateModel(
            name='NamedReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=120, verbose_name='中文名')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='英文名')),
                ('aliases', models.CharField(blank=True, max_length=300, verbose_name='别名')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('condition', models.TextField(blank=True, verbose_name='反应条件')),
                ('mechanism', models.TextField(blank=True, verbose_name='机理描述')),
                ('exam_tips', models.TextField(blank=True, verbose_name='考研考点')),
                ('scope', models.TextField(blank=True, verbose_name='适用范围')),
                ('limitations', models.TextField(blank=True, verbose_name='使用限制')),
                ('reference', models.TextField(blank=True, verbose_name='参考来源')),
                ('equation_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('equation'), verbose_name='反应方程式图')),
                ('mechanism_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('mechanism'), verbose_name='机理图')),
                ('thumbnail_img', models.FileField(blank=True, upload_to=reactions.models.ReactionImageUploadTo('thumbnail'), verbose_name='缩略图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('functional_groups', models.ManyToManyField(blank=True, to='reactions.functionalgroup', verbose_name='官能团')),
                ('tags', models.ManyToManyField(blank=True, to='reactions.tag', verbose_name='标签')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='reactions.namedreactioncategory', verbose_name='人名反应分类')),
            ],
            options={
                'verbose_name': '人名反应',
                'verbose_name_plural': '人名反应',
                'ordering': ['name_en', 'name_zh'],
            },
        ),
        migrations.AddField(
            model_name='routestep',
            name='related_named_reactions',
            field=models.ManyToManyField(blank=True, related_name='route_steps', to='reactions.namedreaction', verbose_name='相关人名反应'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='related_named_reactions',
            field=models.ManyToManyField(blank=True, related_name='routes', to='reactions.namedreaction', verbose_name='相关人名反应'),
        ),
        migrations.AddIndex(
            model_name='generalreaction',
            index=models.Index(fields=['slug'], name='reactions_g_slug_b12b43_idx'),
        ),
        migrations.AddIndex(
            model_name='generalreaction',
            index=models.Index(fields=['status'], name='reactions_g_status_3dd0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='generalreaction',
            index=models.Index(fields=['name_zh'], name='reactions_g_name_zh_3e5419_idx'),
        ),
        migrations.AddIndex(
            model_name='generalreaction',
            index=models.Index(fields=['name_en'], name='reactions_g_name_en_e60c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='namedreaction',
            index=models.Index(fields=['slug'], name='reactions_n_slug_7d1519_idx'),
        ),
        migrations.AddIndex(
            model_name='namedreaction',
            index=models.Index(fields=['status'], name='reactions_n_status_1b2c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='namedreaction',
            index=models.Index(fields=['name_zh'], name='reactions_n_name_zh_50b3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='namedreaction',
            index=models.Index(fields=['name_en'], name='reactions_n_name_en_493ad4_idx'),
        ),
    ]
