# Generated by Django 5.2.16 on 2026-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0014_admin_content_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='message_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='消息推送时间'),
        ),
    ]
