# Generated by Django 5.2.16 on 2026-08-03 11:09

import django.db.models.deletion
import reactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reactions', '0015_operations_messaging_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='内容 ID')),
                ('section', models.CharField(choices=[('equation', '方程式图'), ('mechanism', '机理图'), ('condition', '反应条件附图'), ('mechanism_text', '机理文字附图'), ('exam_tips', '考点附图')], max_length=30, verbose_name='图片区域')),
                ('image', models.FileField(upload_to=reactions.models.ReactionGalleryImageUploadTo(), verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='图片说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '反应附图',
                'verbose_name_plural': '反应附图',
                'ordering': ['section', 'sort_order', 'pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'section'], name='reactions_r_content_03af99_idx'), models.Index(fields=['section', 'sort_order'], name='reactions_r_section_90501a_idx')],
            },
        ),
    ]
