# Generated by Django 5.2.16 on 2026-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0016_reaction_multi_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True, verbose_name='统计键')),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='统计名称')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总访问量')),
                ('today_count', models.PositiveIntegerField(default=0, verbose_name='今日访问量')),
                ('today_date', models.DateField(blank=True, null=True, verbose_name='今日日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '访问统计',
                'verbose_name_plural': '访问统计',
                'ordering': ['key'],
            },
        ),
    ]
