# Generated by Django 5.2.16 on 2026-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0017_visit_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionimage',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('redraw', '需重画')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
