# Generated by Django 5.2.16 on 2026-08-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reactions', '0018_image_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='对比标题')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='对比说明')),
                ('reaction_a_object_id', models.PositiveIntegerField(verbose_name='反应 A ID')),
                ('reaction_b_object_id', models.PositiveIntegerField(verbose_name='反应 B ID')),
                ('substrate_difference', models.TextField(blank=True, verbose_name='适用底物差异')),
                ('condition_difference', models.TextField(blank=True, verbose_name='反应条件差异')),
                ('product_difference', models.TextField(blank=True, verbose_name='主要产物差异')),
                ('exam_patterns', models.TextField(blank=True, verbose_name='常见考法')),
                ('pitfalls', models.TextField(blank=True, verbose_name='易错点')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reaction_a_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparison_a_set', to='contenttypes.contenttype', verbose_name='反应 A 类型')),
                ('reaction_b_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparison_b_set', to='contenttypes.contenttype', verbose_name='反应 B 类型')),
            ],
            options={
                'verbose_name': '易混反应对比',
                'verbose_name_plural': '易混反应对比',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='专题名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='专题简介')),
                ('learning_goals', models.TextField(blank=True, verbose_name='学习目标')),
                ('exam_focus', models.TextField(blank=True, verbose_name='考试重点')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('general_reactions', models.ManyToManyField(blank=True, related_name='study_topics', to='reactions.generalreaction', verbose_name='常见有机反应')),
                ('named_reactions', models.ManyToManyField(blank=True, related_name='study_topics', to='reactions.namedreaction', verbose_name='人名反应')),
                ('routes', models.ManyToManyField(blank=True, related_name='study_topics', to='reactions.syntheticroute', verbose_name='合成路线')),
            ],
            options={
                'verbose_name': '考研专题',
                'verbose_name_plural': '考研专题',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
