# Generated by Django 5.2.16 on 2026-08-20 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reactions', '0019_study_topics_and_comparisons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_fav_reaction',
        ),
        migrations.RemoveConstraint(
            model_name='studyprogress',
            name='unique_progress_reaction',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='studynote',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='studyprogress',
            name='reaction',
        ),
        migrations.AddField(
            model_name='favorite',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='内容 ID'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='内容 ID'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='studyprogress',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='内容 ID'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_fav_content'),
        ),
        migrations.AddConstraint(
            model_name='studyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_progress_content'),
        ),
    ]
