# Generated by Django 5.2.16 on 2026-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0020_user_tools_gfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestep',
            name='is_key_step',
            field=models.BooleanField(default=False, verbose_name='关键步骤'),
        ),
        migrations.AddField(
            model_name='syntheticroute',
            name='related_functional_groups',
            field=models.ManyToManyField(blank=True, related_name='routes', to='reactions.functionalgroup', verbose_name='目标官能团'),
        ),
    ]
