# Generated by Django 5.2.16 on 2026-08-20 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0021_routestep_is_key_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', '导入'), ('publish', '发布'), ('archive', '归档'), ('cleanup', '清理'), ('other', '其他')], max_length=20, verbose_name='批次类型')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('object_count', models.PositiveIntegerField(default=0, verbose_name='对象数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '内容批次',
                'verbose_name_plural': '内容批次',
                'ordering': ['-created_at'],
            },
        ),
    ]
